apiVersion: batch/v1
kind: Job
metadata:
  name: prime-checker-job
spec:
  template:
    spec:
      containers:
      - name: prime-app
        image: your-docker-id/prime-app:latest
        imagePullPolicy: Always
      restartPolicy: Never